/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ExecuteRemediation': EventHandler<never, never>
    'ChaosMonkey': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }>, never>
    'ApproveFix': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string }> | ApiResponse<404, { error: string }>, { topic: 'incident.approved'; data: never }>
    'AnalyzeIncident': EventHandler<never, never>
    'AlertWebhook': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; alertId: string; status: string }>, { topic: 'incident.detected'; data: never }>
  }
    
}